### ISSUE TITLE
Thank you for this!!!

### ISSUE THREAD

**Issue by loicknuchel** [goyalarchit/elm-dagre#2]
Just opening this issue to thank you for this lib!
I just integrated it into [Azimutt](https://azimutt.app) ([code](https://github.com/azimuttapp/azimutt/pull/158/files#diff-b952fc7494407c3ccefcb0981474b98ef092a5796789e90bb4db91377fe59b0aR82)) and it works perfectly :clap: 

I'm only using the engine, not the render, pretty glad you exposed it :wink: 

Everything works perfectly but there is just one thing I don't understand, in the `coordDict` in `GraphLayout` I get much more values than nodes, that's strange to me as the key is supposed to be the `NodeId`. In my example I have 12 nodes, 65 edges and I got 78 values in the `coordDict`.
Do you know why? If not, no problem, everything is working as expected otherwise.

Thanks!

**Comment by goyalarchit** [comment]
I am glad that you found the library helpful. 

So the additional `66 (78-12)` values are bend points for the edges. These additional vertices are called dummy vertices. They do not appear in the layout but act as a bend point for long edges. The associated list of dummy vertices for each edge is returned in the `controlPtsDict`. For more details about the algorithm, refer to the resources given in the [wiki ](https://github.com/goyalarchit/elm-dagre/wiki). I hope this helps.

**Comment by loicknuchel** [comment]
Very clear! Thank you for this quick answer :+1:
